language: node_js
node_js:
  - 'node'
addons:
  apt:
    packages:
      - libgconf-2-4
install:
  - npm install
cache:
  # cache npm modules
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm run cy:verify
script:
  - npm run test:coverage
